"""empty message

Revision ID: a20d9677cac2
Revises: 
Create Date: 2023-11-23 08:46:04.249367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20d9677cac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('data_nasc', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('tel', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(length=80), nullable=False),
    sa.Column('adm', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnh', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh'),
    sa.UniqueConstraint('id')
    )
    op.create_table('passageiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deficiencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pass', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pass'], ['passageiro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_moto', sa.Integer(), nullable=True),
    sa.Column('placa', sa.String(length=45), nullable=False),
    sa.Column('renavam', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=45), nullable=False),
    sa.Column('marca', sa.String(length=45), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['id_moto'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id_moto')
    )
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pass', sa.Integer(), nullable=True),
    sa.Column('id_moto', sa.Integer(), nullable=True),
    sa.Column('id_pag', sa.Integer(), nullable=True),
    sa.Column('id_ve', sa.Integer(), nullable=True),
    sa.Column('embarque', sa.String(length=60), nullable=False),
    sa.Column('desembarque', sa.String(length=60), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('aceitacao', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_moto'], ['motorista.id'], ),
    sa.ForeignKeyConstraint(['id_pag'], ['pagamento.id'], ),
    sa.ForeignKeyConstraint(['id_pass'], ['passageiro.id'], ),
    sa.ForeignKeyConstraint(['id_ve'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem')
    op.drop_table('veiculo')
    op.drop_table('pagamento')
    op.drop_table('passageiro')
    op.drop_table('motorista')
    op.drop_table('user')
    # ### end Alembic commands ###
